var hierarchy =
[
    [ "advertising_report", "structadvertising__report.html", null ],
    [ "bt_address", "structbt__address.html", null ],
    [ "completed_packet", "structcompleted__packet.html", null ],
    [ "HciDecoder", "class_hci_decoder.html", null ],
    [ "IHciFrame", "class_i_hci_frame.html", [
      [ "hci_acl", "structhci__acl.html", null ],
      [ "IHciCommandFrame", "class_i_hci_command_frame.html", [
        [ "ctrl_bsb_host_buffer_size_cmd", "structctrl__bsb__host__buffer__size__cmd.html", null ],
        [ "ctrl_bsb_read_class_of_device_cmd", "structctrl__bsb__read__class__of__device__cmd.html", null ],
        [ "ctrl_bsb_set_event_filter_cmd", "structctrl__bsb__set__event__filter__cmd.html", null ],
        [ "ctrl_bsb_set_event_mask_cmd", "structctrl__bsb__set__event__mask__cmd.html", null ],
        [ "ctrl_bsb_write_class_of_device_cmd", "structctrl__bsb__write__class__of__device__cmd.html", null ],
        [ "ctrl_bsb_write_extended_inquiry_response_cmd", "structctrl__bsb__write__extended__inquiry__response__cmd.html", null ],
        [ "ctrl_bsb_write_iac_lap_cmd", "structctrl__bsb__write__iac__lap__cmd.html", null ],
        [ "ctrl_bsb_write_inquiry_mode_cmd", "structctrl__bsb__write__inquiry__mode__cmd.html", null ],
        [ "ctrl_bsb_write_inquiry_scan_activity_cmd", "structctrl__bsb__write__inquiry__scan__activity__cmd.html", null ],
        [ "ctrl_bsb_write_inquiry_scan_type_cmd", "structctrl__bsb__write__inquiry__scan__type__cmd.html", null ],
        [ "ctrl_bsb_write_le_host_support_cmd", "structctrl__bsb__write__le__host__support__cmd.html", null ],
        [ "ctrl_bsb_write_local_name_cmd", "structctrl__bsb__write__local__name__cmd.html", null ],
        [ "ctrl_bsb_write_page_scan_type_cmd", "structctrl__bsb__write__page__scan__type__cmd.html", null ],
        [ "ctrl_bsb_write_page_timeout_cmd", "structctrl__bsb__write__page__timeout__cmd.html", null ],
        [ "ctrl_bsb_write_scan_enable_cmd", "structctrl__bsb__write__scan__enable__cmd.html", null ],
        [ "ctrl_bsb_write_simple_pairing_mode_cmd", "structctrl__bsb__write__simple__pairing__mode__cmd.html", null ],
        [ "ctrl_bsb_write_voice_settings_cmd", "structctrl__bsb__write__voice__settings__cmd.html", null ],
        [ "informational_read_local_extended_features_cmd", "structinformational__read__local__extended__features__cmd.html", null ],
        [ "le_create_connection_cmd", "structle__create__connection__cmd.html", null ],
        [ "le_read_remote_used_features_cmd", "structle__read__remote__used__features__cmd.html", null ],
        [ "le_remove_device_from_resolving_list_cmd", "structle__remove__device__from__resolving__list__cmd.html", null ],
        [ "le_set_advertising_data_cmd", "structle__set__advertising__data__cmd.html", null ],
        [ "le_set_advertising_parameters_cmd", "structle__set__advertising__parameters__cmd.html", null ],
        [ "le_set_event_mask_cmd", "structle__set__event__mask__cmd.html", null ],
        [ "le_set_random_address_cmd", "structle__set__random__address__cmd.html", null ],
        [ "le_set_scan_enable_cmd", "structle__set__scan__enable__cmd.html", null ],
        [ "le_set_scan_parameters_cmd", "structle__set__scan__parameters__cmd.html", null ],
        [ "link_control_disconnect_cmd", "structlink__control__disconnect__cmd.html", null ],
        [ "link_control_inquiry_cmd", "structlink__control__inquiry__cmd.html", null ],
        [ "vendor_specific_cmd", "structvendor__specific__cmd.html", null ],
        [ "void_cmd", "structvoid__cmd.html", null ],
        [ "write_default_link_policy_settings_cmd", "structwrite__default__link__policy__settings__cmd.html", null ]
      ] ],
      [ "IHciEventFrame", "class_i_hci_event_frame.html", [
        [ "command_status", "structcommand__status.html", null ],
        [ "CommandComplete", "class_command_complete.html", null ],
        [ "disconnection_complete_event", "structdisconnection__complete__event.html", null ],
        [ "extended_inquiry_result_event", "structextended__inquiry__result__event.html", null ],
        [ "inquiry_complete_event", "structinquiry__complete__event.html", null ],
        [ "le_meta_advertising_report_event", "structle__meta__advertising__report__event.html", null ],
        [ "le_meta_connection_complete_event", "structle__meta__connection__complete__event.html", null ],
        [ "number_of_completed_packet_event", "structnumber__of__completed__packet__event.html", null ]
      ] ]
    ] ],
    [ "IHciResponseFrame", "class_i_hci_response_frame.html", [
      [ "ctrl_bsb_read_class_of_device_response_cmd", "structctrl__bsb__read__class__of__device__response__cmd.html", null ],
      [ "ctrl_bsb_read_extended_inquiry_response_response_cmd", "structctrl__bsb__read__extended__inquiry__response__response__cmd.html", null ],
      [ "ctrl_bsb_read_iac_lap_response_cmd", "structctrl__bsb__read__iac__lap__response__cmd.html", null ],
      [ "ctrl_bsb_read_inquiry_mode_response_cmd", "structctrl__bsb__read__inquiry__mode__response__cmd.html", null ],
      [ "ctrl_bsb_read_inquiry_scan_activity_response_cmd", "structctrl__bsb__read__inquiry__scan__activity__response__cmd.html", null ],
      [ "ctrl_bsb_read_inquiry_scan_type_response_cmd", "structctrl__bsb__read__inquiry__scan__type__response__cmd.html", null ],
      [ "ctrl_bsb_read_le_host_support_response_cmd", "structctrl__bsb__read__le__host__support__response__cmd.html", null ],
      [ "ctrl_bsb_read_local_name_response_cmd", "structctrl__bsb__read__local__name__response__cmd.html", null ],
      [ "ctrl_bsb_read_page_scan_type_response_cmd", "structctrl__bsb__read__page__scan__type__response__cmd.html", null ],
      [ "ctrl_bsb_read_page_timeout_response_cmd", "structctrl__bsb__read__page__timeout__response__cmd.html", null ],
      [ "ctrl_bsb_read_scan_enable_response_cmd", "structctrl__bsb__read__scan__enable__response__cmd.html", null ],
      [ "ctrl_bsb_read_simple_pairing_mode_response_cmd", "structctrl__bsb__read__simple__pairing__mode__response__cmd.html", null ],
      [ "ctrl_bsb_read_voice_settings_response_cmd", "structctrl__bsb__read__voice__settings__response__cmd.html", null ],
      [ "informational_read_bd_addr_response_cmd", "structinformational__read__bd__addr__response__cmd.html", null ],
      [ "informational_read_buffer_size_response_cmd", "structinformational__read__buffer__size__response__cmd.html", null ],
      [ "informational_read_local_extended_features_response_cmd", "structinformational__read__local__extended__features__response__cmd.html", null ],
      [ "informational_read_local_supported_cmd_response_cmd", "structinformational__read__local__supported__cmd__response__cmd.html", null ],
      [ "informational_read_local_version_information_response_cmd", "structinformational__read__local__version__information__response__cmd.html", null ],
      [ "le_read_buffer_size_response_cmd", "structle__read__buffer__size__response__cmd.html", null ],
      [ "le_read_local_supported_features_response_cmd", "structle__read__local__supported__features__response__cmd.html", null ],
      [ "le_read_white_list_response_cmd", "structle__read__white__list__response__cmd.html", null ],
      [ "status_response_cmd", "structstatus__response__cmd.html", null ]
    ] ],
    [ "le_advertising_report", "structle__advertising__report.html", null ],
    [ "le_advertising_report_event_t", "structle__advertising__report__event__t.html", null ],
    [ "le_meta_event", "structle__meta__event.html", null ]
];